steps:
  - id: setup
    name: fishtownanalytics/dbt:0.19.1
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          echo "[TOOL INFORMATION]"
          dbt --version
          echo $$sakey > ./dbt-sa.json 2>/dev/null
          echo "[INSTALLING DEPENDENCIES]"
          dbt deps --profiles-dir ./
          echo "[TESTING CONNECTION]"
          dbt debug --profiles-dir ./
          echo "[DBT RUN]"
          dbt run --profiles-dir ./ --no-version-check
    secretEnv: ['sakey']
availableSecrets:
  secretManager:
    - versionName: projects/sada-brian-suk-sandbox/secrets/dbt-sa/versions/1
      env: sakey